### ISSUE TITLE
@conda-forge-admin, please add user @danielbrown2

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/funcparserlib-feedstock#14]
@conda-forge-admin, please add user @danielbrown2

_Originally posted by @danielbrown2 in https://github.com/conda-forge/funcparserlib-feedstock/issues/13#issuecomment-1678262989_

**Comment by danielbrown2** [comment]
Thanks @dhirschfeld! Are you or another admin able to merge that pull request?

**Comment by dhirschfeld** [comment]
I'm not a maintainer so can't merge, but hopefully someone from @conda-forge/core can help.
